### ISSUE TITLE
Add Officer section to the About page (card component & layout)

### ISSUE THREAD

**Issue by WillBAnders** [ufssd/ufssd-website#18]
Add an Officer section to the About page. This section contains a list of officers including their name, position, and picture, which will be controlled by a card component.

## Requirements

 - Component: Each officer/position will be displayed in a card that should be a separate component (see sketch below). This should contain the position title at the top, then a picture, and then their name. The bottom row may contain any links and/or contact info such as personal website, GitHub, or LinkedIn.
 - Layout: The cards should be displayed in a responsive grid (3 columns on desktop, 1 on mobile). The cards should transition smoothly across different widths.

![image](https://github.com/ufssd/ufssd-website/assets/35618116/758531b9-ff88-4664-ba14-163dd6210c84)

**Comment by Phantom0110** [comment]
<img width="1159" alt="Screenshot 2023-11-03 211942" src="https://github.com/ufssd/ufssd-website/assets/146048575/7cbb87e5-572b-4fe8-b229-54772bd82612">
This is how the cards look.
