### ISSUE TITLE
Images on officer section not loading properly

### ISSUE THREAD

**Issue by Brian-Magnuson** [ufssd/ufssd-website#42]
On the about page, some of the images for the officers are not displaying properly. The files for these images exist, but they do not appear to be formatted correctly. E.g., `public/public/officers/Ranger_Chenore.jpg` exists, but trying to view it in any application does not work.

## Requirements

Replace the images for these officers:
- Eric Navar
- Ranger Chenore
- Trevor Richardson

Check to make sure the images display correctly.

![image](https://github.com/ufssd/ufssd-website/assets/92892499/f220232e-d38f-4375-8b2b-553d3142a700)
![image](https://github.com/ufssd/ufssd-website/assets/92892499/1a51019c-1fb1-4113-a6be-7fec13be4813)

**Comment by JavierM333** [comment]
#43
